# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenSenseTool' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod "PickerPopupDialog"
  pod 'MarqueeLabel'

  # Pods for GenSenseTool

  target 'GenSenseToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenSenseToolUITests' do
    # Pods for testing
  end

end


target 'GenSClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  pod "PickerPopupDialog"
  pod 'MarqueeLabel'

#  target 'GenScnseClipTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'GenSenseToolUITests' do
#    # Pods for testing
#  end

end

