# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenSenseTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "PickerPopupDialog"
  # Pods for GenSenseTool

  target 'GenSenseToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenSenseToolUITests' do
    # Pods for testing
  end

end
